/**
 * Workser SDK — one client for everything a Workser project owns.
 *
 * The design constraint that shapes all of this: an app generated by an AI
 * agent should be able to reach its own database, business data, connected
 * accounts, files and automations **without being configured**. Workser
 * provisions the credentials into the project's environment, so the intended
 * usage is:
 *
 * ```ts
 * import { workser } from '@workser/app';
 * const orders = await workser.business.orders.list();
 * ```
 *
 * No keys in source, no setup step, nothing for a non-technical owner to paste.
 *
 * Security posture, briefly:
 *  • refuses to hold a secret key in a browser (see `BrowserSecretError`)
 *  • refuses to send a key to a non-https, non-loopback origin
 *  • never logs, echoes or embeds a credential — errors are redacted
 *  • parameterised SQL only
 *  • idempotency keys on writes, so an automatic retry cannot double-charge
 */
import { resolveConfig, isBrowser, isClientRuntime, type WorkserConfig } from './config.js';
import { HttpClient, SDK_VERSION } from './http.js';
import { Business } from './resources/business.js';
import { Connect } from './resources/connect.js';
import { Storage } from './resources/storage.js';
import { Auth } from './resources/auth.js';
import { Db } from './resources/db.js';
import { Workflows } from './resources/workflow.js';

export class Workser {
  readonly projectId: string;
  /** Commerce and content records — the project's own business. */
  readonly business: Business;
  /** Gmail, Slack, Sheets, Stripe … connected once, usable by every app. */
  readonly connect: Connect;
  /** Project file storage. */
  readonly storage: Storage;
  /** Project end-user authentication. */
  readonly auth: Auth;
  /** The project's Postgres database. */
  readonly db: Db;
  /** Workflow automation — hand work off so it outlives the request. */
  readonly workflows: Workflows;

  private readonly http: HttpClient;

  constructor(config: WorkserConfig = {}) {
    const resolved = resolveConfig(config);
    this.projectId = resolved.projectId;
    this.http = new HttpClient(resolved);

    this.business = new Business(this.http, resolved.projectId);
    this.connect = new Connect(this.http, resolved.projectId);
    this.storage = new Storage(this.http, resolved.projectId);
    this.auth = new Auth(this.http, resolved.projectId);
    this.db = new Db(this.http, resolved.projectId);
    this.workflows = new Workflows(
      this.http,
      resolved.projectId,
      resolved.workflowBaseUrl,
      resolved.workflowApiKey,
    );
  }

  /**
   * Escape hatch for a Core API route the SDK does not wrap yet.
   *
   * Core API moves faster than this package is republished, and an app being
   * blocked on an npm release to call an endpoint it is already entitled to
   * would be a bad trade. Uses the same auth, retries and redaction.
   */
  request<T = unknown>(
    path: string,
    opts?: Parameters<HttpClient['request']>[1],
  ): Promise<T> {
    return this.http.request<T>(path, opts);
  }
}

export function createClient(config: WorkserConfig = {}): Workser {
  return new Workser(config);
}

/**
 * Zero-config singleton.
 *
 * Constructed lazily on first property access, so importing this module can
 * never throw — a missing `WORKSER_PROJECT_ID` surfaces at the call that
 * needed it, with a message naming the variable, rather than as an opaque
 * module-load crash in a serverless cold start.
 */
let singleton: Workser | undefined;

export const workser: Workser = new Proxy({} as Workser, {
  get(_target, prop, receiver) {
    singleton ??= new Workser();
    const value = Reflect.get(singleton, prop, singleton);
    return typeof value === 'function' ? value.bind(singleton) : value;
  },
});

/** Reset the lazy singleton. Tests only. */
export function __resetSingleton(): void {
  singleton = undefined;
}

export { SDK_VERSION, isBrowser, isClientRuntime };
export type { WorkserConfig };
export {
  WorkserError,
  BrowserSecretError,
  type WorkserErrorCode,
  type WorkserRequestInfo,
} from './errors.js';
export { redact, redactValue } from './redact.js';
export { BusinessResource, type ListParams } from './resources/business.js';
export type { Toolkit, Connection, ToolSchema } from './resources/connect.js';
export type { StoredFile } from './resources/storage.js';
export type { AuthUser } from './resources/auth.js';
export type { TableInfo } from './resources/db.js';
export type { Workflow, Execution } from './resources/workflow.js';
